### ISSUE TITLE
Player specific XP

### ISSUE THREAD

**Issue by FayeAlephNil** [elifoster/MC-SkillPoints#2]
We are going to have to add in a way to make the XP player specific. I think the best way to do this is to just add an object (PlayerXP) onto the player.dat with all the data we need

**Comment by elifoster** [comment]
Duplicate of "Saving XP per player and skill using NBT data" in #1. Closing. And as I said in IRC, that is going to happen last, after all of the XP generation code is finished. It'll be easiest to implement it then.
